    <div id="sidebar" class="page-sidebar">
        <div class="page-sidebar-scroll">
        	<div class="sidebar-section">
            	<p>Navigation</p>
                <a href="#" class="sidebar-close"></a>
            </div>
            <div class="sidebar-header">
                <a href="index.html" class="sidebar-logo"></a>
               
               
            </div>
            
            <div class="navigation-items">
                <div class="nav-item">
                    <a href="../zhl/index" class="home-nav">主页<em class="selected-nav"></em></a>
                </div> 
                <div class="nav-item">
                    <a href="#" class="features-nav submenu-deploy">个人中心<em class="dropdown-nav"></em></a>
                    <div class="nav-item-submenu">
                    	<a href="../news/shownews">文章<em class="unselected-sub-nav"></em></a>
                        <a href="../word/showword">单词<em class="unselected-sub-nav"></em></a>
                        <a href="../word/showexample">好友<em class="unselected-sub-nav"></em></a>
                        <a href="../word/showexample">资料<em class="unselected-sub-nav"></em></a>
                    </div>
                </div> 
                <div class="nav-item">
                    <a href="#" class="media-nav submenu-deploy">英语四级<em class="dropdown-nav"></em></a>
                    <div class="nav-item-submenu">
                    	<a href="../news/shownews">四级文章<em class="unselected-sub-nav"></em></a>
                        <a href="../word/showword">四级单词<em class="unselected-sub-nav"></em></a>
                        <a href="../word/showexample">四级短语<em class="unselected-sub-nav"></em></a>
                        <a href="../word/showexample">四级例题<em class="unselected-sub-nav"></em></a>
                    </div>
                </div> 
                <div class="nav-item">
                    <a href="#" class="media-nav submenu-deploy">英语六级<em class="dropdown-nav"></em></a>
                    <div class="nav-item-submenu">
                    	<a href="../news/shownews">六级文章<em class="unselected-sub-nav"></em></a>
                        <a href="../word/showword">六级单词<em class="unselected-sub-nav"></em></a>
                        <a href="../word/showexample">六级短语<em class="unselected-sub-nav"></em></a>
                        <a href="../word/showexample">六级例题<em class="unselected-sub-nav"></em></a>
                    </div>
                </div> 
                <div class="nav-item">
                    <a href="#" class="close-nav">关闭菜单<em class="unselected-nav"></em></a>
                </div> 
                <div class="sidebar-decoration"></div>
            </div>
        	

        	<div class="sidebar-section copyright-sidebar">
            	<p>Copyright 2014. All rights reserved.</p>
            </div>                  
        </div>
    </div>